### ISSUE TITLE
SSL Check fails for no apparent reason

### ISSUE THREAD

**Issue by markdieselcore** [spatie/ssl-certificate#18] opened 2017-03-22 18:08 UTC
When checking a completely valid url, the package will frequently fail and throw exceptions, then suddenly work with the next request. This is a frequent issue.

**Comment by markdieselcore** [comment] 2017-03-22 18:26
I'm getting a "hostDoesNotExist" exception.

Originally I thought it was a server configuration issue on the domain's end.

I'm creating a Lumen API that handles multiple free services. You can try it out for yourself here: https://api.genesisdesignsonline.com/isitsecure/v1?api_key=dqHASveXc63dVHmoyCa4AJUHmzjxobNmPjqsAacGPZHUh8GXyW&url=spatie.be

Try submitting the same URL multiple times and you'll see what I mean.

Using Forge/Lumen PHP 7.1.

**Comment by mallardduck** [comment] 2017-04-10 22:35
Hmm. Not sure if you've worked out the issues, but I've tried to hit the URL provided rapidly and haven't seen the issues yet. Getting 100% `SUCCESS` in my testing.

**Comment by nsouto** [comment] 2017-04-27 22:37
I haven't been able to duplicate the issue either.

**Comment by freekmurze** [comment] 2017-04-27 22:49
Closing this for now because the problem can't be reproduced.

**Closed by freekmurze** 2017-04-27 22:49 UTC
Labels: help wanted
